name: Docker Build and Push

on:
  pull_request:
    branches: [ "main" ]

jobs:

  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Build and Push to ACR
      uses: azure/docker-login@v1
      with:
        login-server: ${{ steps.terraform.outputs.acr_name }}.azurecr.io
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}
      
    - name: Build and push the image
      run: |
        docker build -t ${{ steps.terraform.outputs.acr_name }}.azurecr.io/weather-app:${{ github.sha }} ./remix-weather-app
        docker push ${{ steps.terraform.outputs.acr_name }}.azurecr.io/weather-app:${{ github.sha }}


